# Generated by Django 4.2.6 on 2023-12-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='files',
            field=models.ImageField(blank=True, upload_to='static/files/'),
        ),
    ]
