# Generated by Django 4.2.6 on 2023-12-08 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Writers',
        ),
    ]
